export default { 
    products: [
        {
          id: 0,
          name: "Refined Steel Shoes",
          image: "https://picsum.photos/640/480",
          price: "849.00",
          status: false,
          quantity: 82644,
        },
        {
          id: 1,
          name: "Tasty Concrete Chips",
          image: "https://picsum.photos/640/480",
          price: "762.00",
          status: true,
          quantity: 57587,
        },
        {
          id: 2,
          name: "Awesome Soft Fish",
          image: "https://picsum.photos/640/480",
          price: "633.00",
          status: false,
          quantity: 51117,
        },
        {
          id: 3,
          name: "Gorgeous Concrete Car",
          image: "https://picsum.photos/640/480",
          price: "728.00",
          status: false,
          quantity: 56,
        },
        {
          id: 4,
          name: "Fantastic Fresh Fish",
          image: "https://picsum.photos/640/480",
          price: "364.00",
          status: true,
          quantity: 7373,
        },
        {
          id: 5,
          name: "Gorgeous Metal Soap",
          image: "https://picsum.photos/640/480",
          price: "654.00",
          status: true,
          quantity: 26,
        },
        {
          id: 6,
          name: "Tasty Fresh Pizza",
          image: "https://picsum.photos/640/480",
          price: "795.00",
          status: true,
          quantity: 61,
        },
        {
          id: 7,
          name: "Tasty Concrete Towels",
          image: "https://picsum.photos/640/480",
          price: "513.00",
          status: false,
          quantity: 36,
        },
        {
          id: 8,
          name: "Awesome Metal Computer",
          image: "https://picsum.photos/640/480",
          price: "741.00",
          status: false,
          quantity: 29,
        },
        {
          id: 9,
          name: "Small Rubber Cheese",
          image: "https://picsum.photos/640/480",
          price: "471.00",
          status: true,
          quantity: 42,
        },
        {
          id: 10,
          name: "Handcrafted Soft Salad",
          image: "https://picsum.photos/640/480",
          price: "824.00",
          status: true,
          quantity: 86,
        },
        {
          id: 11,
          name: "Licensed Steel Soap",
          image: "https://picsum.photos/640/480",
          price: "611.00",
          status: false,
          quantity: 14,
        },
        {
          id: 12,
          name: "Handmade Frozen Ball",
          image: "https://picsum.photos/640/480",
          price: "821.00",
          status: false,
          quantity: 64,
        },
        {
          id: 13,
          name: "Handmade Plastic Table",
          image: "https://picsum.photos/640/480",
          price: "894.00",
          status: true,
          quantity: 94,
        },
        {
          id: 14,
          name: "Generic Fresh Gloves",
          image: "https://picsum.photos/640/480",
          price: "156.00",
          status: false,
          quantity: 13,
        },
        {
          id: 15,
          name: "Generic Soft Keyboard",
          image: "https://picsum.photos/640/480",
          price: "933.00",
          status: true,
          quantity: 64,
        },
        {
          id: 16,
          name: "Intelligent Granite Table",
          image: "https://picsum.photos/640/480",
          price: "694.00",
          status: false,
          quantity: 65,
        },
        {
          id: 17,
          name: "Small Soft Shirt",
          image: "https://picsum.photos/640/480",
          price: "797.00",
          status: false,
          quantity: 22,
        },
        {
          id: 18,
          name: "Rustic Metal Table",
          image: "https://picsum.photos/640/480",
          price: "841.00",
          status: false,
          quantity: 98,
        },
        {
          id: 19,
          name: "Incredible Soft Mouse",
          image: "https://picsum.photos/640/480",
          price: "828.00",
          status: false,
          quantity: 63,
        },
      ]
     }